<template>
  <div class="main">
    <img
      src="https://static.igem.wiki/teams/4627/wiki/other-background.png"
      class="other-background"
    />
    <div class="page-title">Parts</div>
    <content-decorate style="margin-top: -20vh" :navigation="navigation">
      <text-with-image
      main-title="OVERVIEW"
      :text-content="[
        'Our team tried to improve the thermostability of a new wild type enzyme, PEase(consist of Ceres and Demetra), and successfully improved its thermostability greatly. Since the increase of temperature has a promoting effect on the degradation of PE plastics, this study also provides a more efficient method for the degradation of PE plastics.',
        'This year, we designed 66 basic parts, including two wild-type PEase Ceres and Demetra. Firstly, we tested these two proteins separately, of which Demetra was tested with 7 different carrier and 3 different Strains. Luckily, Ceres was very successful after one trial expression.',
        'Through rational design, we obtained 64 mutants of Ceres on the basis of the wild type. They are designed on four different mutation principles, 35 of which were designed based on disulfide bonds. Ten of them were designed based on flexible sites. 9 were designed based on single-point mutations to improve stability of hydrophobic core. And 10 were mutated at multiple sites by adding excellent mutants generated by the design above to better improve the thermostability of Ceres. All components are designed by ourselves and experimentally tested to ensure their feasibility.'
      ]"></text-with-image>
      <text-with-image
      main-title="Basic Parts"
      :text-content="[
        'We tested Ceres and Demetra, and obtained good system of expression. The mutants in the Improved Part are designed according to the CDS of wild-type in the Basic Part. However, we only made a series of mutational improvements to Ceres due to time.'
      ]"></text-with-image>
      <tabel-com
      :chart-data="[
        ['No.', 'Name', 'Description', 'Designer', 'Length(bp)', 'Improved Part'],
        ['1', 'BBa_K4627002', 'Ceres', 'tjusls-china 2023', 2067, ''],
        [2, 'BBa_K4627026', 'Demetra', 'tjusls-china 2023', 2097, ''],
        [3, 'BBa_K4627005', 'A5-disulfide bonds', 'tjusls-china 2023', 2067, '√'],
        ['4',	'BBa_K4627007',	'A7- disulfide bonds',	'tjusls-china 2023',	'2067',	'√'],
        [5, 'BBa_K4627008', 'A8- disulfide bonds', 'tjusls-china 2023', '2067', '√'],
        [6, 'BBa_K4627009', 'A9- disulfide bonds', 'tjusls-china 2023', '2067', '√'],
        [7,'BBa_K4627011', 'A11- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [8, 'BBa_K4627012', 'A12- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [9, 'BBa_K4627014', 'A14- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [10, 'BBa_K4627015', 'A15- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [11, 'BBa_K4627017', 'A17- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [12, 'BBa_K4627018', 'B1- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [13, 'BBa_K4627019', 'B2- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [14, 'BBa_K4627023', 'B6- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [15, 'BBa_K4627024', 'B7- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [16, 'BBa_K4627026', 'B9- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [17, 'BBa_K4627027', 'B10- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [18, 'BBa_K4627029', 'B12- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [19, 'BBa_K4627031', 'B14- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [20, 'BBa_K4627032', 'B15- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [21, 'BBa_K4627033', 'B16- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [22, 'BBa_K4627035', 'B18- disulfide bonds', 'tjusls-china 2023', '2067','√'],
        [23, 'BBa_K4627037', 'R2- Flexible site', 'tjusls-china 2023', '2067','√'],
        [24, 'BBa_K4627038', 'R3- Flexible site', 'tjusls-china 2023', '2067','√'],
        [25, 'BBa_K4627040', 'R5- Flexible site', 'tjusls-china 2023', '2067','√'],
        [26, 'BBa_K4627041', 'R6- Flexible site', 'tjusls-china 2023', '2067','√'],
        [27, 'BBa_K4627042', 'R7- Flexible site', 'tjusls-china 2023', '2067','√'],
        [28, 'BBa_K4627043', 'R8- Flexible site', 'tjusls-china 2023', '2067','√'],
        [29, 'BBa_K4627044', 'R9- Flexible site', 'tjusls-china 2023', '2067','√'],
        [30, 'BBa_K4627045', 'R10- Flexible site', 'tjusls-china 2023', '2067','√'],
        [31, 'BBa_K4627048', 'zc-3- Hydrophobic center', 'tjusls-china 2023', '2067','√'],
        [32, 'BBa_K4627050', 'zc-5- Hydrophobic center', 'tjusls-china 2023', '2067','√'],
        [33, 'BBa_K4627052', 'zc-7- Hydrophobic center', 'tjusls-china 2023', '2067','√'],
        [34, 'BBa_K4627053', 'zc-8- Hydrophobic center', 'tjusls-china 2023', '2067','√'],
        [35, 'BBa_K4627054', 'zc-9- Hydrophobic center', 'tjusls-china 2023', '2067','√'],
        [36, 'BBa_K4627056', 'T2- combination of multiple methods', 'tjusls-china 2023', '2067','√'],
        [37, 'BBa_K4627057', 'T3- combination of multiple methods', 'tjusls-china 2023', '2067','√']
      ]"></tabel-com>
      <text-with-image
      main-title="Part Collection"
      :text-content="[
        'Here are the five mutants that achieved the greatest improvement in thermostability, where thermostability increases by more than 7%.'
      ]"></text-with-image>
      <tabel-com :chart-data="[
        ['No.', 'Name', 'Description', 'Designer', 'Length(bp)'],
        [1, 'BBa_K4627008', 'A8- disulfide bonds', 'tjusls-china 2023', '2067',],
        [2, 'BBa_K4627053', 'zc-8- Hydrophobic center', 'tjusls-china 2023', '2067',],
        [3, 'BBa_K4627044', 'R9- Flexible site', 'tjusls-china 2023', '2067',],
        [4,'BBa_K4627026', 'B9- disulfide bonds', 'tjusls-china 2023', '2067',],
        [5, 'BBa_K4627048', 'zc-3- Hydrophobic center', 'tjusls-china 2023', '2067',]
      ]"></tabel-com>
    </content-decorate>
  </div>
</template>
  
  <script setup>
  import tabelCom from "@/components/table-com.vue"
  import textWithImage from "@/components/text-with-image.vue";
import ContentDecorate from "@/components/content-decorate.vue";
const navigation = [];
</script>
  
<style scoped>
.main {
  width: 100%;
  position: relative;
  display: flex;
  align-items: center;
  flex-direction: column;
  background-color: #cbe8fe;
}
.other-background {
  width: 100%;
  height: 100vh;
}
.main-content {
  position: relative;
  width: 80%;
  padding: 20px 40px;
  overflow: visible;
}
.content {
  width: 80%;
  display: flex;
  margin-bottom: 40px;
}
.side-bar {
  width: 20%;
}
.page-title {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  font-size: 60px;
  font-weight: 700;
  letter-spacing: 3px;
  display: flex;
  height: calc(80vh - 70px);
  align-items: center;
  justify-content: center;
}
</style>